// Generated by CoffeeScript 1.9.3
(function() {
  var should, sut;

  sut = require('../src/index.coffee');

  should = require('should');

  describe('Writing Node with CoffeeScript', function() {
    it('is easy to get started testing... or is it?', function() {
      return true;
    });
    return it('can access exported functions in other modules', function() {
      console.log(sut.greeting('Marcus'));
      return sut.greeting('Marcus').should.equal('Hello Marcus Hammarberg§!');
    });
  });

}).call(this);
