// Generated by CoffeeScript 1.9.3
(function() {
  var greeting;

  greeting = function(name) {
    return "Hello " + name + " Hammarberg!";
  };

  console.log(greeting("Marcus Hammarberg"));

  module.exports.greeting = greeting;

}).call(this);
